apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: springboot-web
          ports:
            - containerPort: 8082